### ISSUE TITLE
Not possible to add multiple steps indicators on the same page

### ISSUE THREAD

**Issue by romanlytvyn** [huextrat/steps_indicator#2]
Currently it's not possible to use multiple steps indicators on the same page.
Selected step indicator is wrapped in a `Hero` widget with hardcoded `tag: 'selectedStep'`
As a result the framework produces an exception `There are multiple heroes that share the same tag within a subtree.`

**Comment by huextrat** [comment]
Thank for reporting the issue, version 1.0.1 is coming soon with a fix for this issue.

**Comment by huextrat** [comment]
Fix in v1.0.1: https://pub.dev/packages/steps_indicator
