### ISSUE TITLE
Add animation 

### ISSUE THREAD

**Issue by KyleKun** [huextrat/steps_indicator#3]
Hello! This package is great, thanks for the hard work! 

Would it be possible to add an animation when going to the next step?

A really simple thing, just filling the color slowly until the next step to show more clearly to users that they advanced to the next step. 

Thanks in advance!

**Comment by huextrat** [comment]
Hi!

Yes it's something I wanted for this package but due to lack of time it hasn't been done yet.
I'm open to the proposal if anyone wants to do it ;)

I'll work on it in the coming weeks but there's a lot of refacto to do I think to add a nice animation.

**Comment by KyleKun** [comment]
Thanks for the quick response! Looking forward to it 😀

**Comment by huextrat** [comment]
Hey @KyleKun, I've initiated a big part of the feature on ongoing PR #4 
If you have some time to try it and send some feedback, will be great thanks ;)

**Comment by KyleKun** [comment]
Hey @huextrat, first of all, thanks again for the quick update!

Just tested it and the line's animation is perfect!

 But if I use the step's animation together, this is what it looks like when going to the previous step: [gif](https://i.imgur.com/zLe71rR.gif)

**Comment by KyleKun** [comment]
In fact, it wouldn't be a problem using the same color for thel lines and step, but it would be nice if the animation didn't conflict with the line's color if they are different

**Comment by huextrat** [comment]
Thanks for the feedback. Indeed I had seen for the problem of the step animation when going to the previous step. I will improve it to have something better ;)

**Comment by huextrat** [comment]
@KyleKun Hey !

I've updated the animation for the steps that seem much better to me personally, what do you think?

**Comment by KyleKun** [comment]
@huextrat Much better!!

Just a small detail, is there a way to prevent the layout to adjust itself when the animation occurs? I think the step animation resizing affects the height of the container and it "bounces", but I am not sure if this would be better to be dealt by my code or by the lib, take a look: [gif](https://i.imgur.com/rtERgr4.gif)

**Comment by huextrat** [comment]
Yes sure I'll do it soon and then release 1.1.0 😉

**Comment by KyleKun** [comment]
Yay, thank you again! 😀😀
